# Generated by Django 5.2.4 on 2025-07-31 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_commenter_alter_attachment_options_article_islike_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admin',
            table='blog_admin',
        ),
        migrations.AlterModelTable(
            name='article',
            table='blog_article',
        ),
        migrations.AlterModelTable(
            name='attachment',
            table='blog_attachment',
        ),
        migrations.AlterModelTable(
            name='commenter',
            table='blog_commenter',
        ),
        migrations.AlterModelTable(
            name='user',
            table='blog_user',
        ),
    ]
