# Generated by Django 5.2.4 on 2025-08-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
