# Generated by Django 5.2.4 on 2025-08-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_content_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='display_style',
            field=models.CharField(choices=[('default', 'Default'), ('full-width', 'Full Width'), ('float-left', 'Float Left'), ('float-right', 'Float Right')], default='default', max_length=20),
        ),
    ]
