# Generated by Django 5.2.4 on 2025-08-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_attachment_caption_attachment_display_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='image_sizes',
            field=models.JSONField(blank=True, help_text='Stores URLs for different responsive image sizes in format {width: url}', null=True),
        ),
    ]
