# Generated by Django 5.2.7 on 2025-10-12 03:48

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comment_like_delete_commenter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True)),
            ],
            options={
                'db_table': 'blog_category',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='content_json',
        ),
        migrations.AddField(
            model_name='admin',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor')], default='editor', max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='articles', to='blog.category'),
        ),
    ]
